name: alabatrap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  device_preview: ^1.2.0
  boxicons: ^2.1.3
  crystal_navigation_bar: ^1.0.0
  iconly: ^1.0.1
  flexify: ^2.1.1
  anim_search_bar: ^2.0.3
  sizer: ^2.0.15
  shared_preferences: ^2.2.3
  http: ^1.2.1
  firebase_core: ^3.1.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  dio: ^5.5.0+1
  rx_shared_preferences: ^3.1.0
  dartx: ^1.2.0
  flutter_facebook_auth_platform_interface: ^6.0.0
  flutter_facebook_auth: ^7.0.1
  toastification: ^2.0.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

