name: giahuylearnbe
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.11
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  equatable: ^2.0.5
  firedart: ^0.9.8
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.15.0
  postgres: ^2.6.2
  redis: ^4.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
